#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { compileToC } from "@ts-gbdk/compiler";

function printHelp(): void {
  process.stdout.write(
    [
      "ts-gbdk CLI",
      "",
      "Commands:",
      "  init <projectName> [parentDir]   create a new game project",
      "  transpile <input.ts> [projectDir]",
      "  build <input.ts> [projectDir] [--target gb|gbc]",
      "  help",
    ].join("\n") + "\n",
  );
}

// ─── sdk init ────────────────────────────────────────────────────────────────

function init(projectName: string, parentDir: string): number {
  if (!/^[A-Za-z][A-Za-z0-9_-]*$/.test(projectName)) {
    process.stderr.write(
      `error: project name must start with a letter and contain only letters, digits, _ or -\n`,
    );
    return 1;
  }

  const projectDir = resolve(process.cwd(), parentDir, projectName);

  if (existsSync(projectDir)) {
    process.stderr.write(`error: directory already exists: ${projectDir}\n`);
    return 1;
  }

  // Resolve the SDK root (two levels up from this file: packages/cli/dist -> sdk root)
  const sdkRoot = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "..",
    "..",
  );

  mkdirSync(join(projectDir, "src"), { recursive: true });
  mkdirSync(join(projectDir, "assets"), { recursive: true });
  mkdirSync(join(projectDir, "gbdk-out", "src"), { recursive: true });
  mkdirSync(join(projectDir, "gbdk-out", "build"), { recursive: true });

  // src/game.ts
  writeFileSync(
    join(projectDir, "src", "game.ts"),
    gameTemplate(projectName),
    "utf8",
  );

  // tsconfig.json – paths relative to the new project dir pointing into the SDK
  const relToSdk = relative(projectDir, sdkRoot).replace(/\\/g, "/");
  writeFileSync(
    join(projectDir, "tsconfig.json"),
    tsconfigTemplate(relToSdk),
    "utf8",
  );

  // package.json
  writeFileSync(
    join(projectDir, "package.json"),
    JSON.stringify(
      {
        name: projectName,
        version: "0.1.0",
        private: true,
        type: "module",
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  // .gitignore
  writeFileSync(
    join(projectDir, ".gitignore"),
    ["gbdk-out/src/", "gbdk-out/build/", "node_modules/", ""].join("\n"),
    "utf8",
  );

  process.stdout.write(
    [
      `created project: ${projectDir}`,
      ``,
      `next steps:`,
      `  cd ${projectName}`,
      `  # edit src/game.ts`,
      `  node <sdk>/packages/cli/dist/index.js transpile src/game.ts .`,
      `  GBDK_HOME=<path> node <sdk>/packages/cli/dist/index.js build src/game.ts . --target=gb`,
    ].join("\n") + "\n",
  );

  return 0;
}

function gameTemplate(projectName: string): string {
  return [
    `// ${projectName} – generated by ts-gbdk-sdk`,
    `// Edit this file to build your game.`,
    `// Types: u8, i8, u16, i16, bool, void`,
    `// External GBDK functions must be declared with 'declare function'.`,
    ``,
    `declare function joypad(): u8;`,
    `declare function move_sprite(id: u8, x: u8, y: u8): void;`,
    ``,
    `let playerX: u8 = 80;`,
    `let playerY: u8 = 72;`,
    ``,
    `const SPEED: u8 = 1;`,
    ``,
    `// updateFrame is called once per frame by the generated game loop.`,
    `function updateFrame(): void {`,
    `  const pad: u8 = joypad();`,
    `  if ((pad & 0x20) !== 0) { playerX = playerX - SPEED; }`,
    `  if ((pad & 0x10) !== 0) { playerX = playerX + SPEED; }`,
    `  if ((pad & 0x40) !== 0) { playerY = playerY - SPEED; }`,
    `  if ((pad & 0x80) !== 0) { playerY = playerY + SPEED; }`,
    `  move_sprite(0, playerX, playerY);`,
    `}`,
    ``,
  ].join("\n");
}

function tsconfigTemplate(relToSdk: string): string {
  return (
    JSON.stringify(
      {
        extends: `${relToSdk}/tsconfig.base.json`,
        compilerOptions: {
          noEmit: true,
          strict: true,
          typeRoots: [`${relToSdk}/node_modules/@types`],
        },
        include: [`${relToSdk}/packages/types/index.d.ts`, "src/**/*.ts"],
      },
      null,
      2,
    ) + "\n"
  );
}

function transpile(inputPath: string, projectDir: string): number {
  const absIn = resolve(process.cwd(), inputPath);
  const absProjectDir = resolve(process.cwd(), projectDir);
  const absOut = join(absProjectDir, "gbdk-out");
  const absSrc = join(absOut, "src");
  const absBuild = join(absOut, "build");

  const source = readFileSync(absIn, "utf8");
  const result = compileToC({ filePath: absIn, source });

  if (result.diagnostics.length > 0) {
    for (const d of result.diagnostics) {
      process.stderr.write(`warning: ${d}\n`);
    }
  }

  mkdirSync(absOut, { recursive: true });
  mkdirSync(absSrc, { recursive: true });
  mkdirSync(absBuild, { recursive: true });

  const base = baseNameNoExt(absIn);
  writeFileSync(join(absSrc, `${base}.h`), result.headerSource, "utf8");
  writeFileSync(join(absSrc, `${base}.c`), result.cSource, "utf8");
  writeFileSync(join(absOut, "Makefile"), makefileTemplate(base), "utf8");

  process.stdout.write(`generated gbdk-out for ${base} in ${absOut}\n`);
  return 0;
}

function build(inputPath: string, projectDir: string, target: string): number {
  const absProjectDir = resolve(process.cwd(), projectDir);
  const absOut = join(absProjectDir, "gbdk-out");
  const absSrc = join(absOut, "src");
  const base = baseNameNoExt(resolve(process.cwd(), inputPath));

  const transpileCode = transpile(inputPath, projectDir);
  if (transpileCode !== 0) return transpileCode;

  const outputRom = join(absOut, "build", `${base}.${target}`);
  const inputC = join(absSrc, `${base}.c`);
  const lcc = findLccExecutable();
  const args = ["-o", outputRom, inputC];

  if (target === "gbc") {
    args.unshift("-Wm-yC");
  }

  const result = spawnSync(lcc, args, {
    stdio: "inherit",
    cwd: absOut,
    shell: process.platform === "win32",
  });

  if (result.error) {
    process.stderr.write(`failed to run lcc: ${result.error.message}\n`);
    return 1;
  }

  return result.status ?? 1;
}

function findLccExecutable(): string {
  const gbdkHome = process.env.GBDK_HOME;
  if (gbdkHome) {
    const winExe = join(gbdkHome, "bin", "lcc.exe");
    const unixExe = join(gbdkHome, "bin", "lcc");
    if (existsSync(winExe)) return winExe;
    if (existsSync(unixExe)) return unixExe;
  }

  return "lcc";
}

function makefileTemplate(projectName: string): string {
  return [
    "ifndef GBDK_HOME",
    "$(error Please set GBDK_HOME to your GBDK root path)",
    "endif",
    "",
    "LCC = $(GBDK_HOME)/bin/lcc",
    "PROJECTNAME = " + projectName,
    "CSOURCES = $(wildcard src/*.c)",
    "",
    "all: gb",
    "",
    "gb:",
    "\t$(LCC) -o build/$(PROJECTNAME).gb $(CSOURCES)",
    "",
    "gbc:",
    "\t$(LCC) -Wm-yC -o build/$(PROJECTNAME).gbc $(CSOURCES)",
    "",
    "clean:",
    "\trm -f build/*.gb build/*.gbc build/*.ihx build/*.map build/*.sym src/*.o",
    "",
  ].join("\n");
}

function baseNameNoExt(filePath: string): string {
  const name = filePath.substring(
    Math.max(filePath.lastIndexOf("/"), filePath.lastIndexOf("\\")) + 1,
  );
  const dot = name.lastIndexOf(".");
  return dot >= 0 ? name.slice(0, dot) : name;
}

function main(): number {
  const [, , cmd, ...args] = process.argv;

  if (!cmd || cmd === "help" || cmd === "--help" || cmd === "-h") {
    printHelp();
    return 0;
  }

  if (cmd === "init") {
    if (args.length < 1) {
      process.stderr.write("usage: ts-gbdk init <projectName> [parentDir]\n");
      return 1;
    }
    return init(args[0], args[1] ?? process.cwd());
  }

  if (cmd === "transpile") {
    if (args.length < 1) {
      process.stderr.write(
        "usage: ts-gbdk transpile <input.ts> [projectDir]\n",
      );
      return 1;
    }

    return transpile(args[0], args[1] ?? process.cwd());
  }

  if (cmd === "build") {
    if (args.length < 1) {
      process.stderr.write(
        "usage: ts-gbdk build <input.ts> [projectDir] [--target gb|gbc]\n",
      );
      return 1;
    }

    const targetArg = args.find((x) => x.startsWith("--target="));
    const target = targetArg ? targetArg.split("=")[1] : "gb";
    if (target !== "gb" && target !== "gbc") {
      process.stderr.write("unsupported target. use gb or gbc\n");
      return 1;
    }

    const projectDir =
      args[1] && !args[1].startsWith("--") ? args[1] : process.cwd();
    return build(args[0], projectDir, target);
  }

  process.stderr.write(`unknown command: ${cmd}\n`);
  printHelp();
  return 1;
}

process.exit(main());
